from dotenv import load_dotenv
import os

load_dotenv()

# VECTOR DB
VECTOR_DB_PATH = os.getenv("VECTOR_DB_PATH")
COATER_DB_PATH = os.getenv("COATER_DB_PATH")

# RAG MODEL PATH
EMBEDDING_MODEL_PATH = os.getenv("EMBEDDING_MODEL_PATH")
RERANKER_MODEL_PATH = os.getenv("RERANKER_MODEL_PATH")

# TTS MODEL
BARK_MODEL_PATH = os.getenv("BARK_MODEL_PATH")
BARK_VOICE_SEMANTIC_PROMPT = os.getenv("BARK_VOICE_SEMANTIC_PROMPT")
BARK_VOICE_COARSE_PROMPT = os.getenv("BARK_VOICE_COARSE_PROMPT")
BARK_VOICE_FINE_PROMPT = os.getenv("BARK_VOICE_FINE_PROMPT")

# STT MODEL
STT_MODEL_PATH = os.getenv('STT_MODEL_PATH')
